# Generated by Django 5.1.6 on 2025-02-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_alter_lunchitem_lunch_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchitem',
            name='lunch_option',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.option'),
        ),
        migrations.AlterField(
            model_name='lunchitem',
            name='other_option',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
