# Generated by Django 5.1.6 on 2025-02-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_alter_lunchitem_lunch_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchitem',
            name='other_option',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
