# Generated by Django 5.1.6 on 2025-02-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0013_alter_lunchitem_options_alter_lunchitem_other_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchitem',
            name='lunch_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.option'),
        ),
        migrations.AlterField(
            model_name='lunchitem',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.student'),
        ),
    ]
