# Generated by Django 5.1.6 on 2025-02-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0014_alter_lunchitem_lunch_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchitem',
            name='lunch_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.option'),
        ),
        migrations.AlterField(
            model_name='lunchitem',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.student'),
        ),
    ]
