# Generated by Django 5.1.6 on 2025-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0018_alter_lunchitem_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchitem',
            options={'get_latest_by': 'lunch_date', 'ordering': ['-lunch_option', '-student_name']},
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
